### ISSUE TITLE
WebDriverException: disconnected: unable to send message to renderer

### ISSUE THREAD

**Issue by mariohik** [MicrosoftEdge/EdgeWebDriver#104]
I have two computers, one using Stable Edge and one using Edge Dev Channel.
Yesterday afternoon, I started getting the exception below on the computer with Edge Dev. 

```
OpenQA.Selenium.WebDriverException: disconnected: unable to send message to renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: MicrosoftEdge=116.0.1938.43)
at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(OpenQA.Selenium.Response errorResponse, System.String commandToExecute) at offset 306
at OpenQA.Selenium.WebDriver.Execute(System.String driverCommandToExecute, System.Collections.Generic.Dictionary`2 parameters) at offset 74
at OpenQA.Selenium.WebDriver.FindElement(System.String mechanism, System.String value) at offset 33
at OpenQA.Selenium.By.<.ctor>b__11_0(OpenQA.Selenium.ISearchContext context)
at OpenQA.Selenium.By.FindElement(OpenQA.Selenium.ISearchContext context) at offset 1
at OpenQA.Selenium.WebDriver.FindElement(OpenQA.Selenium.By by) at offset 29
at SeleniumExtras.WaitHelpers.ExpectedConditions.<>c__DisplayClass17_0.<InvisibilityOfElementLocated>b__0(OpenQA.Selenium.IWebDriver driver)
at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](System.Func`2 condition, System.Threading.CancellationToken token) at offset 154
```
I am using DriverManager to always get the version of EdgeWebDriver compatible with my browser.

```c#
new DriverManager().SetUpDriver(new EdgeConfig());
```

**Comment by mariohik** [comment]
I tried using Chrome on the same machine and it works fine.

**Comment by busybee25** [comment]
Came up with the same error, it's intermittent error but happens more frequently on Edge V116. Will follow this issue, seeking a solution.
