### ISSUE TITLE
Unable to launch URL with Edge (Edge117.0.2045.12) with selenium 4.10

### ISSUE THREAD

**Issue by neletolus** [MicrosoftEdge/EdgeWebDriver#111]
(Sorry I created the wrong issue earlier. That one is already closed.)

When I tried to launch edge with url, I faced the following exception.

```
Exception in thread "main" java.lang.IllegalArgumentException: http://:-1/json/version could not be parsed into a proper Uri, missing host
	at org.asynchttpclient.uri.Uri.create(Uri.java:73)
	at org.asynchttpclient.uri.Uri.create(Uri.java:62)
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:147)
	at org.asynchttpclient.Dsl.request(Dsl.java:73)
	at org.openqa.selenium.remote.http.netty.NettyMessages.toNettyRequest(NettyMessages.java:57)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:55)
	at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
	at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
	at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
	at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:97)
	at org.openqa.selenium.devtools.CdpEndpointFinder.getCdpEndPoint(CdpEndpointFinder.java:52)
	at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$3(ChromiumDriver.java:137)
	at java.util.Optional.flatMap(Unknown Source)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:137)
	at org.openqa.selenium.chrome.EdgeDriver.<init>(ChromeDriver.java:59)
	at org.openqa.selenium.chrome.EdgeDriver.<init>(ChromeDriver.java:55)
	at org.openqa.selenium.chrome.EdgeDriver.<init>(ChromeDriver.java:47)
	
```

And I believe that this problem is approximately the same as the following problem with Chrome Driver.
https://github.com/SeleniumHQ/selenium/issues/12457
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4533

I using 
* selenium 4.10.0
* edge 117.0.2045.12
* edge webdriver 117.0.2045.12
* java 11

thanks.

**Comment by bwalderman** [comment]
Fixed in ChromeDriver repo: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4533
