### ISSUE TITLE
Edge beta 119.0.2151.12 crashing after 2 mins of Selenium run

### ISSUE THREAD

**Issue by utk787** [MicrosoftEdge/EdgeWebDriver#121]
I am trying to run tests for Edge Beta 119.0.2151.12 and the browser is crashing after 2 minutes some seconds

Below are the logs
```
Thu Oct 19 14:48:34 IST 2023 === EdgeDriver execution on macOS!!
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Oct 19, 2023 2:48:35 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 119, so returning the closest version found: 115
Thu Oct 19 14:48:35 IST 2023 === Opening edge://version
Thu Oct 19 14:48:46 IST 2023 === Opening https://google.com
Thu Oct 19 14:49:02 IST 2023 === Opening https://spacex.com
Thu Oct 19 14:49:14 IST 2023 === Opening https://tesla.com
Thu Oct 19 14:49:29 IST 2023 === Opening https://apple.com
Thu Oct 19 14:49:43 IST 2023 === Opening https://github.com
Thu Oct 19 14:49:55 IST 2023 === Opening https://youtube.com
Thu Oct 19 14:50:43 IST 2023 === Opening https://twitter.com
Thu Oct 19 14:50:58 IST 2023 === Opening https://reddit.com
Exception in thread "main" org.openqa.selenium.WebDriverException: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: MicrosoftEdge=119.0.2151.12)
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.2.1', java.version: '17.0.2'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [8163a87c0b3841709070c2c0cd02a633, get {url=https://reddit.com}]
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 119.0.2151.12, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:57538}, msedge: {msedgedriverVersion: 119.0.2151.12 (91d55e8e6936..., userDataDir: /var/folders/n0/4_r2y8bn25n...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:57538/devtoo..., se:cdpVersion: 119.0.2151.12, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 8163a87c0b3841709070c2c0cd02a633
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:300)
	at utk.selenium.MSEdge.main(MSEdge.java:22)
```

Found [this](https://techcommunity.microsoft.com/t5/discussions/urgent-edge-canary-just-crashes-at-least-2-min-after-opening/m-p/3949556) discussion for Edge 119 canary and this issue seems to be because of copilot enabled.

**Comment by pm036915** [comment]
We are also seeing this in Edge Beta 119

**Comment by utk787** [comment]
Seems to be fixed in 119 stable.
