### ISSUE TITLE
SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Microsoft Edge failed to start: exited normally.

### ISSUE THREAD

**Issue by Darshan77D** [MicrosoftEdge/EdgeWebDriver#132]
Code 

Map<String, Object> edgePrefs = new HashMap<String, Object>();
edgePrefs.put("profile.default_content_settings.popups", 0);
edgePrefs.put("profile.default_content_setting_values.notifications", 2);
edgePrefs.put("download.default_directory", file1);
edgePrefs.put("profile.default_content_setting_values.automatic_downloads", 1);
edgePrefs.put("download.prompt_for_download", false);
EdgeOptions options = new EdgeOptions();
options.setExperimentalOption("prefs", edgePrefs);
options.addArguments("start-maximized"); // open Browser in maximized mode
options.addArguments("disable-infobars"); // disabling infobars
options.addArguments("--disable-extensions"); // disabling extensions
options.addArguments("--disable-gpu"); // applicable to windows os only
options.addArguments("--disable-dev-shm-usage"); // overcome limited resource problems
options.addArguments("--no-sandbox");
options.addArguments("--remote-debugging-port=5557");
options.setCapability(CapabilityType.ACCEPT_INSECURE_CERTS, true);
WebDriverManager.edgedriver().setup();
driver =new EdgeDriver(options);

Error log:
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Microsoft Edge failed to start: exited normally.
(chrome not reachable)
(The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)

OS -Windows 11
Java -14
Selenium 4.11
Edge version 120

**Comment by bwalderman** [comment]
Thanks for reporting this. I've added it to our internal backlog for investigation.

**Comment by eshravani** [comment]
facing similar issue. Any update on this?

**Comment by nagamuppavarapu-rgare** [comment]
**We are facing similar issue**
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: Microsoft Edge failed to start: crashed.
  (chrome not reachable)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.) 
Host info: host: 'TESTHOST', ip: 'XX.XX.XX.XX'
Build info: version: '4.18.0', revision: 'b6bf9de7cc*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.22'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: MicrosoftEdge, ms:edgeOptions: {args: [--no-sandbox, --disable-dev-shm-usage, --remote-debugging-port=9222], extensions: []}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:139)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:95)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:233)

**Comment by Kiran1975** [comment]
We are facing a similar issue when running the test scripts in Jenkins, but locally working fine.  Please let me know if there is any update on this.
