### ISSUE TITLE
Microsoft Edge failed to start: crashed

### ISSUE THREAD

**Issue by yumao2003** [MicrosoftEdge/EdgeWebDriver#45]
Hi,

I'm trying to use edge driver to launch edge for auto testing but failed, below is the log.

-------------------------------------------------------------------------
Version: 3.58.6

Starting Microsoft Edge WebDriver 104.0.1293.47 (246533a39fec5a167e7729d997877afea075bd86) on port 7440
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
org.openqa.selenium.WebDriverException: unknown error: Microsoft Edge failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so msedgedriver is assuming that msedge has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'xxxxxxxx', ip: 'xxxxxxxxxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: driver.version: EdgeDriver
remote stacktrace: Backtrace:
	Microsoft::Applications::Events::EventProperties::unpack [0x00007FF6C6434182+26370]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00007FF6C63894E2+339106]
	Ordinal0 [0x00007FF6C5F17821+620577]
	Ordinal0 [0x00007FF6C5F3FCFA+785658]
	Ordinal0 [0x00007FF6C5F3A8E8+764136]
	Ordinal0 [0x00007FF6C5F74B4F+1002319]
	Ordinal0 [0x00007FF6C5F6F263+979555]
	Ordinal0 [0x00007FF6C5F46070+811120]
	Ordinal0 [0x00007FF6C5F47668+816744]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6C61E2998+128088]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6C61CC2EB+36267]
	Microsoft::Applications::Events::EventProperty::EventProperty [0x00007FF6C61CF30C+48588]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6C6024393+22115]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00007FF6C6390B0B+369355]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00007FF6C63959A4+389476]
	Microsoft::Applications::Events::GUID_t::GUID_t [0x00007FF6C6395AFD+389821]
	Microsoft::Applications::Events::time_ticks_t::time_ticks_t [0x00007FF6C63A0589+40761]
	BaseThreadInitThunk [0x00007FFB629D7034+20]
	RtlUserThreadStart [0x00007FFB62BE2651+33]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:141)
	at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:96)
	at Core.DriverConfigurator.createDriver(DriverConfigurator.java:289)
	at Core.ApplitoolsSeleniumTestRunner.executeTest(ApplitoolsSeleniumTestRunner.java:151)
	at Core.ApplitoolsSeleniumTestRunner.run(ApplitoolsSeleniumTestRunner.java:87)
	at Utils.ParallelRunsHandler$ThreadPoolRunnable.run(ParallelRunsHandler.java:86)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Chris-Challis-i2** [comment]
Quick question: Does the version of Edge WebDriver installed match the version of WebView2-runtime? As far as I can tell, both will need to be 104.0.1293.47, but WebView2 is updated with Windows Updates for the Edge browser so may have got out of step with your version of Edge WebDriver.

**Comment by bwalderman** [comment]
Hi @yumao2003 . It looks like the Edge browser (msedge.exe) may have crashed but there isn't enough information in the log to understand what happened. Can you try running the test again with verbose logging enabled? Add this line before creating a new EdgeDriver or EdgeDriverService:

```java
System.setProperty("webdriver.edge.verboseLogging", "true");
```

Please share the full log output.

**Comment by bwalderman** [comment]
Closing since there hasn't been any recent activity.
