### ISSUE TITLE
Not possible to indicate which profile to use while using Edge via WebDriver

### ISSUE THREAD

**Issue by bwalderman** [MicrosoftEdge/EdgeWebDriver#58]
For almost 2 years this absurd problem persists for which it is not possible to indicate which profile to use while using Edge via WebDriver.
Do you have any news about it? The documentation says it works but it's not true...

You are causing problems for tons of Test Automation developers, while Chrome and Firefox support it without problems!

Here are other threads talking about it, but StackOverflow is full of angry people too!

https://answers.microsoft.com/en-us/microsoftedge/forum/all/how-can-you-set-the-default-profile-in-the-new/ca600054-0c46-426e-92e2-2c071a13a623

Now the state of bug is changed in "This conversation has been locked and limited to collaborators." on https://github.com/SeleniumHQ/selenium/issues/10968

PS) Here is the Java code that does not work, however, after trying all the possible variants or various indications (with or without -, with or without double quotes).

EdgeOptions edgeOptions = new EdgeOptions ();
String userDataDir = QAUtils.getProperty ("browser.edge.user-data-dir");
String userProfileDir = QAUtils.getProperty ("browser.edge.profile-directory");
edgeOptions.addArguments ("user-data-dir =" + userDataDir);
edgeOptions.addArguments ("profile-directory =" + userProfileDir);
EdgeDriver driverEdge = new EdgeDriver (edgeOptions);

_Originally posted by @lukesoftware in https://github.com/MicrosoftEdge/EdgeWebDriver/issues/29#issuecomment-1297189195_

**Comment by bwalderman** [comment]
@lukesoftware, choosing the user data directory and profile is supported in Edge Chromium and works the same way it does with ChromeDriver. Here is a Java sample that I've tested locally. You can verify that Edge is launched with the specified user profile by navigating to `edge://version` and checking the Profile path:

```java
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.edge.EdgeOptions;

public class EdgeDriverTest {
    public static void main(String[] args) throws InterruptedException {
        EdgeOptions edgeOptions = new EdgeOptions();
        edgeOptions.addArguments("--user-data-dir=C:\\TestUserDataDir");
        edgeOptions.addArguments("--profile-directory=Default");
        EdgeDriver driverEdge = new EdgeDriver(edgeOptions);

        driverEdge.navigate().to("edge://version");
        Thread.sleep(5000);

        driverEdge.quit();
    }
}
```

![image](https://user-images.githubusercontent.com/4146725/199794425-1224494c-ec68-4038-92ab-26b163d5318c.png)


Please note that the EdgeDriver class cannot be used to test IE Mode. You must use InternetExplorerDriver for this, and it does not support a custom user data directory like EdgeDriver does. This is known and as tracked by #29

**Comment by lukesoftware** [comment]
Hi Brandon, thanks for your reply

The code you indicated actually works for me without problems. The fact is
that it does not seem to work when, with the same exact parameters, it is
told to use a directory and therefore a profile
already exists (previously created by the browser itself). In this case it
gives the error that I paste below, and it gives it immediately after
opening the browser, even if it is actually using the indicated profile;
however, it is no longer possible to interact with the driver.

I also tried to add the 2 parameters suggested on stackoverflow as a
solution to the "*DevToolsActivePort file doesn't exist*" message but
nothing changes

edgeOptions.addArguments("headless");

I noticed instead that if I add the "headless" option the error does not
occur but I cannot understand if I am using the profile or not in this
case;
I tried to take a screenshot but it only shows a blank page when it should
be on the "edge://version" page instead

Your code was useful for me to think of an alternative way, since I noticed
the fact that the directory indicated, even if it does not already exist,
is then reused the following times, i.e. the browser keeps track of any
user settings in it. linked to that profile, so this could allow me not to
have to create it first, but to update it gradually after the first time.

Thanks for further suggestions, Gianluca

*My code:*

    EdgeOptions edgeOptions = new EdgeOptions();

 edgeOptions.addArguments("--user-data-dir=C:\\Users\\Gianluca\\AppData\\Local\\Microsoft\\Edge\\User
Data");
    edgeOptions.addArguments("--profile-directory=Profile 4");

     //edgeOptions.addArguments("--disable-dev-shm-usage"); // overcome
limited resource problems
     //edgeOptions.addArguments("--no-sandbox"); // Bypass OS security model

     //edgeOptions.addArguments("headless"); with this parameter, no error!

      EdgeDriver driverEdge = new EdgeDriver(edgeOptions);
      driverEdge.navigate().to("edge://version");
      driverEdge.manage().window().maximize();

*Error log:*

Starting Microsoft Edge WebDriver 107.0.1418.26
(801aa30e905471d971868b02ed128260f15a3a04) on port 53856
To submit feedback, report a bug, or suggest new features, please visit
https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping
Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
nov 04, 2022 4:42:32 PM org.openqa.selenium.os.OsProcess destroy



*SEVERE: Unable to kill process Process[pid=5488, exitValue=1]Exception in
thread "main" org.openqa.selenium.SessionNotCreatedException: Could not
start a new session. Response code 500. Message: unknown error: Microsoft
Edge failed to start: exited normally.  (unknown error: DevToolsActivePort
file doesn't exist)  (The process started from msedge location C:\Program
Files (x86)\Microsoft\Edge\Application\msedge.exe is no longer running, so
msedgedriver is assuming that msedge has crashed.)*
Build info: version: '4.1.4', revision: '535d840ee2'
System info: host: 'DESKTOP-xxx', ip: '10.0.2.15', os.name: 'Windows 10',
os.arch: 'amd64', os.version: '10.0', java.version: '11'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName:
MicrosoftEdge, ms:edgeOptions: {args: [--user-data-dir=C:\Users\Gi...,
--profile-directory=Profile 4, --disable-dev-shm-usage, --no-sandbox],
extensions: []}}], desiredCapabilities=Capabilities {browserName:
MicrosoftEdge, ms:edgeOptions: {args: [--user-data-dir=C:\Users\Gi...,
--profile-directory=Profile 4, --disable-dev-shm-usage, --no-sandbox],
extensions: []}}}]
at
org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
at
org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:84)
at
org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:62)
at
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:156)
at
org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
at
org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:248)
at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:164)
at
org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:52)
at org.openqa.selenium.edge.EdgeDriver.<init>(EdgeDriver.java:44)


PS) I tried with and without the use of
io.github.bonigarcia.wdm.WebDriverManager, nothing changes

[image: image.png]


Il giorno gio 3 nov 2022 alle ore 18:40 Brandon Walderman <
***@***.***> ha scritto:
