### ISSUE TITLE
EdgeWebDriver crashes when input text to element which is not text boxes or text areas from EdgeWebDriver107.

### ISSUE THREAD

**Issue by kousuketk** [MicrosoftEdge/EdgeWebDriver#62]
#### Description
when you input text to element which is not text boxes or text areas for example div element, then EdgeWebDriver will crash from EdgeWebDriver107(until 106 it works well).

#### How to reproduce
we can reproduce this error at https://www.google.com/ .
when you input text to div element like below, then EdgeWebDriver will crash from EdgeWebDriver107.

![スクリーンショット 2022-12-07 17 16 34](https://user-images.githubusercontent.com/42241308/206187855-8aa57c50-876c-4b6c-a6e1-aaed349e69a4.png)

![スクリーンショット 2022-12-07 17 15 43](https://user-images.githubusercontent.com/42241308/206187915-763bb818-88d6-4efb-8316-75c21774701b.png)

This is the log I got.
```
RequestError: socket hang up
    at ClientRequest.<anonymous> (/snapshot/command-line-main/node_modules/webdriver/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.emit (node:domain:475:12)
    at ClientRequest.<anonymous> (/snapshot/command-line-main/node_modules/webdriver/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketOnEnd (node:_http_client:471:9)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at connResetException (node:internal/errors:691:14)
    at Socket.socketOnEnd (node:_http_client:471:23)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by bwalderman** [comment]
@kousuketk sending text to a div element will not work since the div elements you highlighted are not ["interactable"](https://w3c.github.io/webdriver/#interactability). This will throw an error although it should not crash the browser. This is the behavior I'm seeing in Edge WebDriver 107.

If you would like to simulate a Google search, try using the <input> element instead.

**Comment by bwalderman** [comment]
Closing since the issue does not appear to repro in 107+.
