### ISSUE TITLE
webdriverio + edgedriver: The uploadFile command is not available in msedge

### ISSUE THREAD

**Issue by MaximWaveOC** [MicrosoftEdge/EdgeWebDriver#97]
Hello team!
Thank you for your work!

We use webdriverio + edgedriver to run autotests.

Our tests work in chrome.
But in Edge:
`Error: The uploadFile command is not available in msedge
    at Browser.uploadFile (\node_modules\webdriverio\build\commands\browser\uploadFile.js:50:15)
    at Browser.wrapCommandFn (\node_modules\@wdio\utils\build\shim.js:137:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)` 
    
  Please advice us how can we solve this problem to test upload file functional. 
  
  `    
  "wdio/cli": "7.25.2",
  "@wdio/local-runner": "7.25.2",
  "@wdio/mocha-framework": "7.25.2",
   "edgedriver": "5.2.1",`
   
   Thanks.

**Comment by valerylebedz** [comment]
Hello, I'm facing the same issue. Any update on this?

**Comment by bwalderman** [comment]
Hi @MaximWaveOC, @valerylebedz.

Edge WebDriver supports the sample file upload command that ChromeDriver does, so this may be a bug in WebDriverIO's API, and not the driver itself.

Can you confirm that the `Browser` object is a Chromium browser object? https://webdriver.io/docs/api/chromium
File upload is a Chromium-specific command so you'll need to make sure WebDriverIO recognizes your driver is Chromium-based. If you are still running into issues after verifying, I'd recommend opening an issue int he WebDriverIO repo: https://github.com/webdriverio/webdriverio

**Comment by d3m1art** [comment]
I have the same issue

```
[MicrosoftEdge 122.0.2365.8 windows #0-4] The uploadFile command is not available in MicrosoftEdge
[MicrosoftEdge 122.0.2365.8 windows #0-4] Error: The uploadFile command is not available in MicrosoftEdge
[MicrosoftEdge 122.0.2365.8 windows #0-4]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[MicrosoftEdge 122.0.2365.8 windows #0-4]     at async setInputFile (/home/runner/work/chrome/chrome/e2e/lib/helpers/utils.ts:61:26)
[MicrosoftEdge 122.0.2365.8 windows #0-4]     at async Context.<anonymous> 

    "wdio-edgedriver-service": "3.0.3",
        "edgedriver": "5.3.10",
     "wdio/cli": "7.25.2", "@wdio/local-runner": "7.25.2", "@wdio/mocha-framework": "7.25.2", "edgedriver": "5.2.1",



```
